### ISSUE TITLE
Options for collapsed service navigation when there is only one nav link

### ISSUE THREAD

**Issue by benjamin-mortimer** [alphagov/di-govuk-one-login-service-header#16]
One service got in touch with us about what to do if their internal navigation contains only one link.

The header will still work in this case and it doesn't produce any accessibility issues, but there may some strangeness in the internal navigation menu's appearance and function on smaller screens (eg mobile).

The menu collapses on smaller screens, and will then open to reveal only a single item.

What should we do about this? It seems acceptable bahviour for the time being, but in a future iteration we may wish to do something like:

+ have the menu default to open if it only contains one item
+ swap in the single navigation link in place of the collapsed menu in the event that there is only one item
+ ...or something else

**Comment by danacotoran** [comment]
This should have been resolved in #28 so we can close this issue now @benjamin-mortimer!
