### ISSUE TITLE
Consider making target area taller for service navigation links

### ISSUE THREAD

**Issue by frankieroberto** [alphagov/di-govuk-one-login-service-header#2]
Hi team!

At the moment, the target area for the service navigation links is just 17px high:

<img width="951" alt="Screenshot 2023-05-17 at 12 36 45" src="https://github.com/alphagov/di-govuk-one-login-service-header/assets/30665/4e48b4d8-f4ea-4004-b403-f0adbf24c27d">

I think we could improve the usability by making the target area the full height of the bar, including the border - which would make it 60px high:

<img width="949" alt="Screenshot 2023-05-17 at 12 38 28" src="https://github.com/alphagov/di-govuk-one-login-service-header/assets/30665/37bd96ad-8306-4bc8-ad36-67009cec96df">

As well as larger target areas generally being good for usability and accessibility, I suspect that the present of the blue border at the bottom will lead users to expect the target area to be bigger here.

One consequence of this will be the focus style. At the moment, the focused links get a yellow background, black text and a black underline. This leads to a double underline + border when the active link is focused:

<img width="921" alt="Screenshot 2023-05-17 at 12 41 26" src="https://github.com/alphagov/di-govuk-one-login-service-header/assets/30665/fa1a53f7-5c66-464c-9553-c0302438c52c">

If the target area was made taller, then the black underline on focus could replace the blue border (for active links):

<img width="1016" alt="Screenshot 2023-05-17 at 12 42 03" src="https://github.com/alphagov/di-govuk-one-login-service-header/assets/30665/ff38f372-16b6-4540-98da-8d44547d8ea2">

Some of the existing services from Department of Education already use a version of this navigation bar (with the taller target areas) in production, like this (showing both an active and focused link):

<img width="1074" alt="Screenshot 2023-05-17 at 12 43 10" src="https://github.com/alphagov/di-govuk-one-login-service-header/assets/30665/8bc1dbb5-9fac-4212-8e90-19e9c1b14588">

I don't think we have any specific research on this, but the design has been in production for a while, and I don’t think any issues have been observed in usability research sessions..

**Comment by benjamin-mortimer** [comment]
Hi Frankie,

Thanks for raising this issue. We'll take a look at this and get back to you after our next planning session (23 May 2023).


All best,

Ben

**Comment by benjamin-mortimer** [comment]
Hi Frankie, apologies for taking longer to get back to you than I originally promised.

We've added this to our backlog and will start working on it soon. I'll keep you updated here with our progress.

Many thanks for raising this - it's a really valuable improvement.


Ben

**Comment by frankieroberto** [comment]
@benjamin-mortimer thanks – look forward to seeing this improvement! 😄

**Comment by danacotoran** [comment]
Closed by https://github.com/alphagov/di-govuk-one-login-service-header/pull/8
