### ISSUE TITLE
Consider using a horizontal navigation for service links on mobile

### ISSUE THREAD

**Issue by frankieroberto** [alphagov/di-govuk-one-login-service-header#3]
Current the design collapses the service navigation links behind a toggleable menu button on mobile:

| Closed | Open |
| ------- | ----- |
| <img width="375" alt="Screenshot 2023-05-17 at 12 46 17" src="https://github.com/alphagov/di-govuk-one-login-service-header/assets/30665/a08aceb4-2a83-45db-ac29-912c09a5b5bc"> | <img width="376" alt="Screenshot 2023-05-17 at 12 47 06" src="https://github.com/alphagov/di-govuk-one-login-service-header/assets/30665/10c2bd51-4d02-43d6-92dc-5a5848081455"> |

I think it’s worth considering at least the option for service teams to use a horizontal navigation layout on mobile.

These have a few advantages:

* easier to see which section you're currently 'in' (as one will be highlighted)
* some users may not notice the Menu button
* quicker to move between sections for repeat users (one less click)

The disadvantages are that they can take up more space, particularly if the number of links or the length of the link text causes them to wrap over 2 lines.

Here’s how it looks on a Department for Education service, where we chose to use a horizontal navigation with wrapping on mobile:

<img width="373" alt="Screenshot 2023-05-17 at 12 51 30" src="https://github.com/alphagov/di-govuk-one-login-service-header/assets/30665/7488ca6e-93df-48d0-b574-bf23dff6f043">

**Comment by benjamin-mortimer** [comment]
Hi Frankie,

Apologies for taking longer to get back to you than I originally promised.

We've decided not to work on this issue for the time being.

We'd like to establish that the set of changes that make the One Login header different to the existing GOV.UK service header are successful before we iterate the design further.

However, we think this is an interesting potential iteration and will keep it in mind when we come to develop the design.

Many thanks for raising this issue.


Ben

**Comment by frankieroberto** [comment]
@benjamin-mortimer no worries - this can be something considered later!
