### ISSUE TITLE
Consider using larger text in service navigation bar

### ISSUE THREAD

**Issue by frankieroberto** [alphagov/di-govuk-one-login-service-header#7]
Hi team!

I had a go at (speculatively) using the header for a future version of our service.

It looked good but I found myself wanting to increase the font size of both the service name (to 24px) and the navigation links (to 19px). This seems more balanced to me?

Here’s a before and after:

| Before | After | 
|----|----|
| <img width="1215" alt="header-before" src="https://github.com/alphagov/di-govuk-one-login-service-header/assets/30665/85610726-9dfe-430b-bc98-fe9d6542b0a0"> | <img width="1215" alt="header-after" src="https://github.com/alphagov/di-govuk-one-login-service-header/assets/30665/5e3622ed-3eb6-4bde-8435-40c0b5a3e370"> |

I guess this might be less possible if services use a log of navigation items or have a very long service name, but for many services, the increased font size might be better?

**Comment by danacotoran** [comment]
Hi @frankieroberto! 

Our UCD team agreed with you and decided to increase font sizes for all the nav links, as well as the service name heading – I implemented the updates in https://github.com/alphagov/di-govuk-one-login-service-header/pull/24.
Font sizes should be more consistent now overall, both on mobile and on larger screens. You should be able to grab the latest styles from the [dist folder](https://github.com/alphagov/di-govuk-one-login-service-header/tree/main/dist/styles). 

I'm going to close this issue now. 
Thanks for your suggestions so far, and let us know any other bits of feedback you may have!
